### ISSUE TITLE
[Testing] add tests

### ISSUE THREAD

**Issue by YUMO9743** [KomachiZ/Emotion-Insight-Analyzer#5]
add tests to new functionalities and fixed funtionalities

**Comment by KomachiZ** [comment]
New cases of sentiment analysis tests for text and upload files have been added:

Basic Functionality Tests (TestSentimentAnalysis - 5 tests)

test_empty_input: Unit test  
test_none_input: Unit test  
test_basic_sentiment (Parameterized test - 3 scenarios): Unit test  
test_chinese_analysis: Functional test  
test_english_emotions: Functional test  

File Processing Tests (TestFileProcessing - 4 tests)

test_text_file_processing: Integration test  
test_large_text_processing: Performance test  
test_word_frequency_impact: Unit test  
fixture: sample_text_content: Test fixture  

Multilingual Support Tests (TestMultilingualSupport - 4 tests)

test_language_specific_features (Parameterized test - 4 languages): Functional test  
English analysis  
Chinese analysis  
French analysis   
Spanish analysis  

Error Handling Tests (TestErrorHandling - 4 tests)

test_invalid_input_type: Exception testing   
test_malformed_text: Boundary testing   
test_mixed_sentiment_text: Functional testing   
test_special_characters: Boundary testing   

Edge Case Testing (TestEdgeCases - 2 tests)

test_repeated_punctuation: Boundary testing   
test_case_sensitivity: Functional testing

**Comment by YUMO9743** [comment]
added test for re-analyze, including basic operation, multi language input, empty imput, special character input, etc.
